services:
  backend:
    build: ./backend
    image: ghcr.io/lem0n4ell0/nestjs-film-backend:prod

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: ghcr.io/lem0n4ell0/nestjs-film-nginx:prod